[package]
name = "basic_example"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.6.10"
ic-cdk-macros = "0.6.10"
ic-stable-structures = { path = "../../../" }
