[package]
name = "task_timer"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic0 = "0.18"
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
ic-stable-structures = { path = "../../../" }
