name: Post Canbench results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  download-results:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-benchmarks.outputs.matrix }}
      pr_number: ${{ steps.set-benchmarks.outputs.pr_number }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - id: set-benchmarks
        run: bash ./scripts/ci_download_canbench_artifacts.sh

  post-comment:
    runs-on: ubuntu-latest
    needs: [download-results]
    strategy:
      matrix: ${{fromJSON(needs.download-results.outputs.matrix)}}
    steps:
      - name: Post comment
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          message: |
            ${{ matrix.benchmark.result }}
          comment-tag: ${{ matrix.benchmark.title }}
          pr-number: ${{ needs.download-results.outputs.pr_number }}
