name: Post Canbench results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  download-results:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-benchmarks.outputs.matrix }}
      pr_number: ${{ steps.set-benchmarks.outputs.pr_number }}
    steps:
      - uses: actions/checkout@v4

      - uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - id: set-benchmarks
        run: bash ./scripts/ci_download_canbench_artifacts.sh

  post-comment:
    runs-on: ubuntu-latest
    needs: [download-results]
    strategy:
      matrix: ${{fromJSON(needs.download-results.outputs.matrix)}}
    steps:
      - name: Post comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ matrix.benchmark.result }}
          comment_tag: ${{ matrix.benchmark.title }}
          pr_number: ${{ needs.download-results.outputs.pr_number }}

