name: Comment on PR
on:
  repository_dispatch:
    types: [post-comment]

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write

    steps:
      - name: Post comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ github.event.client_payload.message }}
          comment_tag: ${{ github.event.client_payload.comment_tag }}
